name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup docker build
      uses: docker/setup-buildx-action@v2.4.0
      
    -  name: Docker Login
       uses: docker/login-action@v2.1.0
       with:
        username: rogeriopd
        password: ${{ secrets.TEST }}
